-- Atualizar o campo 'pais' na tabela 'restaurantes' baseado no 'parentGeoName' do JSON 'avaliacao_json' usando uma tabela auxiliar

-- 1. Criar uma tabela auxiliar de mapeamento cidade -> país
CREATE TEMP TABLE cidade_pais_map (
    cidade TEXT PRIMARY KEY,
    pais TEXT NOT NULL
);

-- 2. Inserir os mapeamentos na tabela auxiliar
INSERT INTO cidade_pais_map (cidade, pais) VALUES
('Akasaka', 'Japão'),
('Amsterdam', 'Holanda'),
('Annandale', 'Austrália'),
('Asakusa', 'Japão'),
('Azabujuban', 'Japão'),
('Balmain', 'Austrália'),
('Bangkok', 'Tailândia'),
('Bergvliet', 'África do Sul'),
('Boston', 'Estados Unidos'),
('Bunkyo', 'Japão'),
('Cebu Island', 'Filipinas'),
('Chicago', 'Estados Unidos'),
('Chiyoda', 'Japão'),
('Chuo', 'Japão'),
('Claremont', 'Austrália'),
('Constantia', 'África do Sul'),
('Daiba', 'Japão'),
('Darlington', 'Austrália'),
('Double Bay', 'Austrália'),
('Drummoyne', 'Austrália'),
('Dubai', 'Emirados Árabes Unidos'),
('Dulwich Hill', 'Austrália'),
('Ebisu', 'Japão'),
('Edgecliff', 'Austrália'),
('Enmore', 'Austrália'),
('Five Dock', 'Austrália'),
('Ginza', 'Japão'),
('Kabukicho', 'Japão'),
('Kenilworth', 'África do Sul'),
('Kojimachi', 'Japão'),
('Kyoto', 'Japão'),
('Leichhardt', 'Austrália'),
('London', 'Reino Unido'),
('Marrickville', 'Austrália'),
('Marunouchi', 'Japão'),
('Meguro', 'Japão'),
('Melbourne', 'Austrália'),
('Minato', 'Japão'),
('Mumbai', 'Índia'),
('Nakano', 'Japão'),
('Negros Island', 'Filipinas'),
('Newtown', 'Austrália'),
('Nha Trang', 'Vietnã'),
('Nihonbashi', 'Japão'),
('Nishiazabu', 'Japão'),
('Nishishinjuku', 'Japão'),
('North Strathfield', 'Austrália'),
('Oak Beach', 'Austrália'),
('Observatory', 'África do Sul'),
('Oshiage', 'Japão'),
('Ota', 'Japão'),
('Ottery', 'África do Sul'),
('Paris', 'França'),
('Port Douglas', 'Austrália'),
('Roppongi', 'Japão'),
('Sendagaya', 'Japão'),
('Setagaya', 'Japão'),
('Shibadaimon', 'Japão'),
('Shibakoen', 'Japão'),
('Shibuya', 'Japão'),
('Shimbashi', 'Japão'),
('Shinagawa', 'Japão'),
('Shinjuku', 'Japão'),
('Shinjuku 3 Chome', 'Japão'),
('Shintomicho', 'Japão'),
('Singapore', 'Singapura'),
('Stanmore', 'Austrália'),
('St Peters', 'Austrália'),
('Sumida', 'Japão'),
('Sydney', 'Austrália'),
('Taito', 'Japão'),
('Takadanobaba', 'Japão'),
('Takanawa', 'Japão'),
('Toranomon', 'Japão'),
('Toshima', 'Japão'),
('Toyosu', 'Japão'),
('Tsukiji', 'Japão'),
('Udagawacho', 'Japão'),
('Ueno', 'Japão'),
('Uenokoen', 'Japão'),
('Venice', 'Itália'),
('Warsaw', 'Polônia'),
('Washington DC', 'Estados Unidos'),
('Watsons Bay', 'Austrália'),
('Woollahra', 'Austrália'),
('Yanaka', 'Japão'),
('Yoyogi', 'Japão'),
('Yurakucho', 'Japão');

-- 3. Atualizar o campo 'pais' com base no mapeamento
UPDATE restaurantes r
SET pais = m.pais
FROM cidade_pais_map m
WHERE (r.avaliacao_json::json ->> 'parentGeoName') = m.cidade;

-- Obs.: Depois de atualizar, a tabela TEMPORÁRIA cidade_pais_map é descartada automaticamente no fim da sessão.