
openapi: 3.0.0
info:
  title: HerokuAPI Patched Stringified
  version: 1.0.2
  description: Versão com detalhesJson como string
servers:
  - url: https://travel-app-experience-b7e9d856670c.herokuapp.com

paths:
  /api/restaurantesPatchedHeroku/{locationId}:
    get:
      operationId: getRestaurantesByLocationIdPatchedString
      summary: Detalhes do restaurante com JSON como string
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do restaurante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RestauranteDetalhadoPatchedString'
        '404':
          description: Restaurante não encontrado

components:
  schemas:
    RestauranteDetalhadoPatchedString:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        nota:
          type: number
        categoria:
          type: string
        location_id:
          type: string
        parent_geo_name:
          type: string
        detalhesJson:
          type: string
          description: Conteúdo JSON do restaurante convertido em string
